"""
PDF export for L.E.A.D.S. — render a memo / case brief (markdown-ish text) to a
clean, printable PDF. Dependency-light (fpdf2, pure-Python, no system libs).

The core Helvetica font is latin-1, which covers most legal text incl. the
section sign §. Non-latin-1 characters (smart quotes, em/en dashes, bullets,
ellipsis) are normalized so output never errors on Unicode.
"""
from __future__ import annotations

import re
from typing import Optional

from fpdf import FPDF
from fpdf.enums import XPos, YPos

_DISCLAIMER = (
    "General legal information, not legal advice. Generated by L.E.A.D.S. "
    "(Legal Education & Analytical Deep-Search). Verify against primary sources."
)

# Normalize common non-latin-1 characters the LLM emits.
_SUBS = {
    "‘": "'", "’": "'", "“": '"', "”": '"',
    "–": "-", "—": "-", "•": "-", "…": "...",
    " ": " ", " ": " ", "​": "", "→": "->",
}


def _san(text: str) -> str:
    if not text:
        return ""
    for k, v in _SUBS.items():
        text = text.replace(k, v)
    # Drop **bold** / *italic* / `code` / markdown link syntax markers.
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    text = re.sub(r"(?<!\*)\*(?!\*)(.+?)\*", r"\1", text)
    text = text.replace("`", "")
    # Anything still outside latin-1 -> closest ascii or '?'.
    return text.encode("latin-1", "replace").decode("latin-1")


class _Doc(FPDF):
    title_text = "L.E.A.D.S."

    def footer(self) -> None:
        self.set_y(-15)
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(120)
        self.multi_cell(0, 3.5, _san(_DISCLAIMER), align="C", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        self.set_text_color(0)


def render(title: str, markdown: str) -> bytes:
    """Render a title + markdown-ish body to PDF bytes."""
    pdf = _Doc()
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.add_page()
    pdf.set_margins(18, 16, 18)

    def cell(h: float, text: str, *, size: float = 10.5, bold: bool = False, indent: float = 0.0) -> None:
        pdf.set_font("Helvetica", "B" if bold else "", size)
        if indent:
            pdf.set_x(18 + indent)
        pdf.multi_cell(0, h, _san(text), new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    cell(8, title or "Untitled", size=16, bold=True)
    pdf.ln(2)
    pdf.set_draw_color(200)
    pdf.line(18, pdf.get_y(), 192, pdf.get_y())
    pdf.ln(4)

    for raw in (markdown or "").splitlines():
        line = raw.rstrip()
        if not line.strip():
            pdf.ln(2.5)
            continue
        m = re.match(r"^(#{1,4})\s+(.*)$", line)
        if m:
            size = {1: 14, 2: 12.5, 3: 11.5, 4: 11}.get(len(m.group(1)), 11)
            pdf.ln(1.5)
            cell(6, m.group(2), size=size, bold=True)
            continue
        mb = re.match(r"^\s*[-*]\s+(.*)$", line)
        if mb:
            cell(5.5, "- " + mb.group(1), indent=6)
            continue
        mn = re.match(r"^\s*(\d+[.)])\s+(.*)$", line)
        if mn:
            cell(5.5, f"{mn.group(1)} {mn.group(2)}", indent=6)
            continue
        cell(5.5, line)

    return bytes(pdf.output())
